---
- name: update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - lvm2
      - python-pip
      - python3-pip
    state: present

- name: update pip2
  pip:
    name: "{{ item }}"
    state: present
    executable: pip2
  with_items:
    - setuptools==38.6.1
    - pip==9.0.3
    - wheel==0.31.0
    - pipenv==2018.5.18
    - virtualenv==16.0.0

- name: update pip3
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - setuptools==38.6.1
    - pip==9.0.3
    - wheel==0.31.0
    - pipenv==2018.5.18
    - virtualenv==16.0.0

- name: add git ppa
  apt_repository:
    repo: "ppa:git-core/ppa"

- name: install git
  apt:
    name: git
    state: present

- name: install boto
  pip:
    name: boto
    state: present
    executable: pip2

- name: install boto3
  pip:
    name: boto3
    state: present
    executable: pip3

- name: install awscli
  pip:
    name: awscli
    state: present
    executable: pip2

- name: configure aws codecommit credentials helper
  blockinfile:
    dest: /etc/gitconfig
    create: yes
    block: |
      [credential]
          helper = !aws codecommit credential-helper $@
          useHttpPath = true

- name: add known hosts
  shell: |
    ssh-keyscan {{ item }} >> /etc/ssh/ssh_known_hosts
  with_items:
    - github.com
    - git-codecommit.us-east-1.amazonaws.com
  changed_when: no
